version: '3'
    
services:
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
            - ./info.sql:/docker-entrypoint-initdb.d/init.sql
    web:
        build: 
            context: .
        ports:
            - "8005:8080"
        depends_on:
            - db

volumes:
    dbdata: